insert into customer(name, surname, username, password, tax_code, role, is_available) values ('Paolo', 'Pacello', 'drPacello', 'dr_pacello99', '00122',1,TRUE);
insert into customer(name, surname, username, password, tax_code, role, is_available) values ('Stefano', 'Ronci', 'stefRon', 'abc123_!', '00133',1,TRUE);
insert into scan(is_available, mc_liter) values (true, 100);
insert into scan(is_available, mc_liter) values (true, 300);
insert into administrator(is_available, role, name, surname, username, password) values (true, 0, 'Luca', 'Rossi', 'lRossiAdmin', 'aaa90_!');
insert into condominium(is_available, address, administrator_id) values (true, 'via Kant 11', 1);
insert into condominium(is_available, address, administrator_id) values (true, 'via Nazionale 111', 1);
insert into apartment(floor_number, is_available, unit_number, condominium_id, customer_id, scan_id) values (3, true, 3, 1, 1, 1);
insert into apartment(floor_number, is_available, unit_number, condominium_id, customer_id, scan_id) values (1, true, 7, 2, 2, 2);
insert into bill(cost, payment_day, Delivering_Day, is_available, scan_id) values (200, '2023-12-15', '2023-10-15', true, 1);
insert into technician(is_available, role, name, surname, username, password) values (true, 3, 'Edwar', 'Azzaro', 'hacker', '123456ee!');
insert into secretary(is_available, role, name, surname, username, password) values (true, 2, 'Giulia', 'Bianchi', 'Giu99', 'giu_99_00');
insert into intervention(is_available, intervention_date, status, type, apartment_id, secretary_id, technician_id) values (true, '2023-12-16', 3, 0, 1, 1, 1);
insert into intervention(is_available, intervention_date, status, type, apartment_id, secretary_id, technician_id) values (true, '2023-12-15', 1, 1, 2, 1, 1);
insert into intervention(is_available, intervention_date, status, type, apartment_id, secretary_id, technician_id) values (true, '2023-12-14', 2, 0, 1, 1, 1);